### ISSUE TITLE
Install composer as a container dependency?

### ISSUE THREAD

**Issue by jasonmccallister** [venveo/docker-baseimage#8]
To minimize the requirements for getting setup with Docker and development at Venveo, we should consider adding support for composer inside of the containers where PHP will be running. 

Thoughts @Mosnar and @carlolaitano?

**Comment by Mosnar** [comment]
I fully support this. I've seen people straight up commit composer files into repos, and it's not clean, but it's super convenient.

**Comment by carlo-laitano** [comment]
I'm for whatever will be easier to set up for most developers. The more straight-forward our environment setups are, the more we can all concentrate on producing quality code :). I say yes 

Carlo Laitano

Lead Designer

mailto:carlo@venveo.com
http://www.venveo.com/

On Sun, Nov 13, 2016 at 1:41 PM Ransom

<
mailto:Ransom notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I fully support this. I've seen people straight up commit composer files into repos, and it's not clean, but it's super convenient.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/venveo/docker-baseimage/issues/8#issuecomment-260207238
, or

**Comment by jasonmccallister** [comment]
Lets do it! These containers are not meant to be used in production, so the xdebug (in 8a9be0399c5b54f630df12629e6247039ac2d983) that @Mosnar added would work well with having composer in the container.
